name: Cypress Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 8 * * *' # Runs every day at 8 AM UTC

jobs:
  lint:
    name: ESLint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm ci
      - run: npx eslint . --ext .js,.mjs,.cjs,.ts --max-warnings=0

  cypress-tests:
    name: Cypress Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm ci
      - run: npm run test:chrome
        env:
          CYPRESS_STANDARD_USER_NAME: ${{ secrets.STANDARD_USER_NAME }}
          CYPRESS_LOCKED_USER_NAME: ${{ secrets.LOCKED_USER_NAME }}
          CYPRESS_PASSWORD: ${{ secrets.PASSWORD }}
          CYPRESS_INVALID_PASSWORD: ${{ secrets.INVALID_PASSWORD }}
          CYPRESS_INVALID_USERNAME: ${{ secrets.INVALID_USERNAME }}
          CYPRESS_DEV_URL: ${{ secrets.DEV_URL }}
          CYPRESS_BASE_PAGE: ${{ secrets.BASE_PAGE }}